export const GET_ARTICLES_LIST_ERROR = 'GET_ARTICLES_LIST_ERROR';
export const GET_ARTICLES_LIST_REQUEST = 'GET_ARTICLES_LIST_REQUEST';
export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS';
export const GET_BOOKS_LIST_ERROR = 'GET_BOOKS_LIST_ERROR';
export const GET_BOOKS_LIST_REQUEST = 'GET_BOOKS_LIST_REQUEST';
export const GET_BOOKS_LIST_SUCCESS = 'GET_BOOKS_LIST_SUCCESS';
